/* ============================================================
   strings.install.js - copy for install.html only.

   Distilled from the plugin's own docs/INSTALLATION.{ko,en,ja}.md
   (sc4sap 0.6.16). Commands, paths, table names, and step content are
   taken from there rather than written fresh. Loaded after strings.js,
   which owns the shared nav and footer copy.
   ============================================================ */

(function () {
  'use strict';
  var S = window.SC4_STRINGS;

  Object.assign(S.ko, {
    insTitle: '설치 가이드',
    insLede: 'Claude Code 세션 안에서 마켓플레이스를 추가하고, 설정 위저드를 한 번 돌리면 끝납니다. MCP 서버는 위저드가 알아서 설치합니다.',
    insDocLink: '전체 원문 문서',
    insBack: '메인으로',

    insReqH: '요구사항',
    insReq1K: 'Node.js',
    insReq1V: '20.0.0 이상',
    insReq2K: 'Claude Code',
    insReq2V: 'CLI 설치 완료 (Max·Pro 구독 또는 API 키)',
    insReq3K: 'SAP 시스템',
    insReq3V: 'ECC 6.0 · S/4HANA On-Premise · S/4HANA Cloud (Public·Private), ADT 활성화',
    insReqNote: 'MCP 서버 <code>abap-mcp-adt-powerup</code> 는 <code>/sc4sap:setup</code> 중 자동으로 설치·설정됩니다. 미리 받아둘 필요가 없습니다.',

    insInstallH: '설치',
    insInstallNote: 'sc4sap 은 아직 공식 Claude Code 플러그인 마켓플레이스에 등록되어 있지 않습니다. 당분간은 저장소를 커스텀 마켓플레이스로 추가한 뒤 설치하세요.',
    insOptAK: '권장',
    insOptAH: '커스텀 마켓플레이스로 추가',
    insOptAP: 'Claude Code 세션 안에서 두 줄을 차례로 실행합니다.',
    insUpdateH: '업데이트할 때',
    insOptBK: '대안',
    insOptBH: '소스에서 설치',
    insOptBP: '클론 후 빌드하고, Claude Code에서 <code>/plugin marketplace add &lt;로컬-경로&gt;</code> 로 해당 디렉터리를 가리킵니다.',

    insSetupH: '설정 위저드',
    insSetupP: '위저드는 한 번에 한 질문만 합니다. 기존 값이 있으면 보여주고 Enter로 유지할 수 있습니다.',
    insW1H: '시스템과 업종',
    insW1P: 'S4 또는 ECC 선택, ABAP 릴리즈 입력, 15개 업종 메뉴에서 선택. 이 값이 SPRO 테이블·BAPI·TCode와 ABAP 문법 게이팅을 결정합니다.',
    insW2H: 'MCP 서버 설치',
    insW2P: '<code>abap-mcp-adt-powerup</code> 을 <code>&lt;PLUGIN_ROOT&gt;/vendor/abap-mcp-adt/</code> 에 클론하고 빌드합니다. 이미 있으면 건너뜁니다.',
    insW3H: '프로필 생성과 연결',
    insW3P: 'alias(<code>KR-DEV</code> 형식 권장)와 tier(<code>DEV</code>·<code>QA</code>·<code>PRD</code>)를 정한 뒤 URL·클라이언트·인증 방식·계정·언어를 하나씩 받습니다. RFC 백엔드는 soap · native · gateway · odata · zrfc 중 선택합니다.',
    insW4H: '연결 검증',
    insW4P: '<code>/mcp</code> 로 재연결한 뒤 <code>GetSession</code> 왕복, 시스템 정보 확인, <code>GetInactiveObjects</code> 로 ADT 권한까지 확인합니다. Claude Code 재시작은 필요 없습니다.',
    insW5H: 'ABAP 유틸 객체 생성',
    insW5P: 'DEV 프로필에서만 설치됩니다. <code>ZMCP_ADT_UTILS</code> 함수그룹과 <code>ZIF_S4SAP_CM</code> · <code>ZCL_S4SAP_CM_*</code> ALV 핸들러를 만듭니다. QA·PRD 에서는 거부하고 CTS 이관 안내를 출력합니다.',
    insW6H: '권한 훅 설치',
    insW6P: '이 단계 없이는 설정이 완료되지 않습니다. <code>block-forbidden-tables.mjs</code>(행 추출 차단)와 <code>tier-readonly-guard.mjs</code>(tier 변이 차단)를 <code>.claude/settings.json</code> 에 등록하고 양쪽 스모크 테스트를 실행합니다.',
    insOptionalH: '선택 단계',
    insOptional1: 'SPRO 설정 추출 - 토큰을 많이 쓰지만 캐시가 이후 작업의 토큰 사용을 크게 줄입니다',
    insOptional2: '커스터마이징 인벤토리 - <code>Z*</code>·<code>Y*</code> 확장과 어펜드 구조를 스캔합니다',
    insOptional3: 'HUD 상태 줄 - 재시작 후 활성 프로필과 tier, 토큰 사용량을 표시합니다',
    insSubH: '서브커맨드',

    insProfileH: '멀티 프로필',
    insProfileP: '한 Claude Code 세션에서 여러 SAP 연결을 다룹니다. 연결 하나가 프로필 하나이고, 프로젝트에는 어느 프로필이 활성인지만 기록됩니다.',
    insTier1: '<b>tier 는 읽기전용 강제의 기준입니다.</b> QA·PRD 프로필에서는 <code>Create*</code> · <code>Update*</code> · <code>Delete*</code> 가 훅과 MCP 서버 두 층에서 차단됩니다.',
    insTier2: '<b>tier 는 변경할 수 없습니다.</b> 바꾸려면 프로필을 지우고 다시 만들어야 합니다.',
    insTier3: '<b>비밀번호는 OS 키체인에 저장됩니다.</b> Windows 자격 증명 관리자 · macOS 키체인 · Linux libsecret. 키체인을 못 쓰는 환경에서는 프로필 env 평문으로 대체하고 경고를 띄웁니다.',

    insDefenseH: '3중 방어',
    insDefenseP: '운영계에 붙이기 전에 가장 먼저 검토되는 부분입니다. 문서가 아니라 코드로 강제됩니다.',
    insL1aH: '행 추출 차단',
    insL1aP: 'Claude Code <code>PreToolUse</code> 훅. 프로필의 <code>blocklistProfile</code> 을 기준으로 민감 테이블의 <code>GetTableContents</code> · <code>GetSqlQuery</code> 를 거부합니다.',
    insL1bH: 'tier 변이 차단',
    insL1bP: 'Claude Code <code>PreToolUse</code> 훅. 매 호출마다 활성 프로필의 <code>SAP_TIER</code> 를 다시 읽어 QA·PRD 의 변경을 막습니다. 상태를 들고 있지 않습니다.',
    insL2H: 'MCP 서버 자체 가드',
    insL2P: '우회할 수 없는 층입니다. 훅이 빠지거나 잘못 설정되어도 <code>abap-mcp-adt-powerup</code> 내부 가드가 항상 동작합니다.',
    insDefenseNote: 'L1 훅은 IO·파싱 오류 시 통과시키고, L2 MCP 가드는 항상 켜져 있습니다. 권장 기본값은 L1a <code>strict</code>, MCP 서버 블록리스트 <code>standard</code> 입니다.',

    insAfterH: '설정 완료 후',
    insAfter1K: '활성 시스템 전환',
    insAfter2K: '법인이나 tier 추가',
    insAfter3K: '프로필 목록',
    insAfter4K: '상태 점검',
    insAfter5K: 'SPRO 재추출',

    insMoreH: '더 읽을거리',
    insMore1: '설치 및 설정 원문',
    insMore2: '기능 상세',
    insMore3: '변경 이력'
  });

  Object.assign(S.en, {
    insTitle: 'Install guide',
    insLede: 'Add the marketplace inside a Claude Code session, run the setup wizard once, and you are done. The wizard installs the MCP server for you.',
    insDocLink: 'Full reference',
    insBack: 'Back to main',

    insReqH: 'Requirements',
    insReq1K: 'Node.js',
    insReq1V: '20.0.0 or newer',
    insReq2K: 'Claude Code',
    insReq2V: 'CLI installed (Max or Pro subscription, or an API key)',
    insReq3K: 'SAP system',
    insReq3V: 'ECC 6.0 · S/4HANA On-Premise · S/4HANA Cloud (Public and Private), with ADT enabled',
    insReqNote: 'The MCP server <code>abap-mcp-adt-powerup</code> is installed and configured automatically during <code>/sc4sap:setup</code>. Nothing to fetch beforehand.',

    insInstallH: 'Installation',
    insInstallNote: 'sc4sap is not on the official Claude Code plugin marketplace yet. For now, add the repository as a custom marketplace and install from it.',
    insOptAK: 'Recommended',
    insOptAH: 'Add as a custom marketplace',
    insOptAP: 'Run both lines inside a Claude Code session.',
    insUpdateH: 'To update later',
    insOptBK: 'Alternative',
    insOptBH: 'Install from source',
    insOptBP: 'Clone and build, then point Claude Code at that directory with <code>/plugin marketplace add &lt;local-path&gt;</code>.',

    insSetupH: 'Setup wizard',
    insSetupP: 'The wizard asks one question at a time. Existing values are shown so you can press Enter to keep them.',
    insW1H: 'System and industry',
    insW1P: 'Choose S4 or ECC, enter the ABAP release, pick an industry from the 15-option menu. These drive the SPRO tables, BAPIs, transaction codes, and ABAP syntax gating.',
    insW2H: 'Install the MCP server',
    insW2P: 'Clones and builds <code>abap-mcp-adt-powerup</code> into <code>&lt;PLUGIN_ROOT&gt;/vendor/abap-mcp-adt/</code>. Skipped if it is already there.',
    insW3H: 'Create a profile and connect',
    insW3P: 'Set an alias (<code>KR-DEV</code> style is suggested) and a tier (<code>DEV</code>, <code>QA</code>, <code>PRD</code>), then supply URL, client, auth type, account, and language one field at a time. Pick an RFC backend from soap, native, gateway, odata, zrfc.',
    insW4H: 'Verify the connection',
    insW4P: 'Reconnect with <code>/mcp</code>, then a <code>GetSession</code> round trip, a system info check, and an ADT authority check via <code>GetInactiveObjects</code>. No Claude Code restart needed.',
    insW5H: 'Create the ABAP utility objects',
    insW5P: 'DEV profiles only. Installs the <code>ZMCP_ADT_UTILS</code> function group plus the <code>ZIF_S4SAP_CM</code> and <code>ZCL_S4SAP_CM_*</code> ALV handlers. On QA and PRD it refuses and prints CTS import guidance instead.',
    insW6H: 'Install the permission hooks',
    insW6P: 'Setup is not complete without this step. Registers <code>block-forbidden-tables.mjs</code> (row-extraction guard) and <code>tier-readonly-guard.mjs</code> (tier mutation guard) in <code>.claude/settings.json</code>, then runs both smoke tests.',
    insOptionalH: 'Optional steps',
    insOptional1: 'SPRO extraction. Token heavy, but the cache cuts token use sharply on everything that follows',
    insOptional2: 'Customization inventory. Scans <code>Z*</code> and <code>Y*</code> enhancements and append structures',
    insOptional3: 'HUD status line. After a restart it shows the active profile, its tier, and token usage',
    insSubH: 'Subcommands',

    insProfileH: 'Multiple profiles',
    insProfileP: 'One Claude Code session can hold several SAP connections. Each connection is a profile; the project only records which one is active.',
    insTier1: '<b>Tier is what enforces read-only.</b> On QA and PRD profiles, <code>Create*</code>, <code>Update*</code>, and <code>Delete*</code> are blocked at two layers, the hook and the MCP server.',
    insTier2: '<b>Tier is immutable.</b> Changing it means removing the profile and adding it again.',
    insTier3: '<b>Passwords live in the OS keychain.</b> Windows Credential Manager, macOS Keychain, Linux libsecret. Where no keychain is available it falls back to plaintext in the profile env and warns you.',

    insDefenseH: 'Three layers of defense',
    insDefenseP: 'This is the first thing reviewed before anything touches a live system. It is enforced in code, not in a policy document.',
    insL1aH: 'Row extraction guard',
    insL1aP: 'A Claude Code <code>PreToolUse</code> hook. Uses the profile\'s <code>blocklistProfile</code> to deny <code>GetTableContents</code> and <code>GetSqlQuery</code> on sensitive tables.',
    insL1bH: 'Tier mutation guard',
    insL1bP: 'A Claude Code <code>PreToolUse</code> hook. Re-reads <code>SAP_TIER</code> from the active profile on every call and denies mutations on QA and PRD. It holds no state.',
    insL2H: 'MCP server guard',
    insL2P: 'The layer you cannot route around. Even if the hooks are missing or misconfigured, the guard inside <code>abap-mcp-adt-powerup</code> is always active.',
    insDefenseNote: 'Both L1 hooks fail open on IO or parse errors; the L2 guard is always on. Typical defaults are <code>strict</code> for L1a and <code>standard</code> for the MCP server blocklist.',

    insAfterH: 'After setup',
    insAfter1K: 'Switch active system',
    insAfter2K: 'Add a company or tier',
    insAfter3K: 'List profiles',
    insAfter4K: 'Health check',
    insAfter5K: 'Re-extract SPRO',

    insMoreH: 'Further reading',
    insMore1: 'Installation reference',
    insMore2: 'Feature detail',
    insMore3: 'Changelog'
  });

  Object.assign(S.ja, {
    insTitle: 'インストールガイド',
    insLede: 'Claude Code セッション内でマーケットプレイスを追加し、セットアップウィザードを一度実行すれば完了します。MCP サーバーはウィザードが自動で導入します。',
    insDocLink: '原文ドキュメント',
    insBack: 'メインへ戻る',

    insReqH: '要件',
    insReq1K: 'Node.js',
    insReq1V: '20.0.0 以上',
    insReq2K: 'Claude Code',
    insReq2V: 'CLI インストール済 (Max・Pro サブスクリプションまたは API キー)',
    insReq3K: 'SAP システム',
    insReq3V: 'ECC 6.0 · S/4HANA On-Premise · S/4HANA Cloud (Public・Private)、ADT 有効',
    insReqNote: 'MCP サーバー <code>abap-mcp-adt-powerup</code> は <code>/sc4sap:setup</code> の途中で自動的にインストール・設定されます。事前準備は不要です。',

    insInstallH: 'インストール',
    insInstallNote: 'sc4sap はまだ公式 Claude Code プラグインマーケットプレイスに登録されていません。当面はリポジトリをカスタムマーケットプレイスとして追加してから導入してください。',
    insOptAK: '推奨',
    insOptAH: 'カスタムマーケットプレイスとして追加',
    insOptAP: 'Claude Code セッション内で 2 行を順に実行します。',
    insUpdateH: '更新するとき',
    insOptBK: '代替',
    insOptBH: 'ソースからインストール',
    insOptBP: 'クローンしてビルドし、Claude Code で <code>/plugin marketplace add &lt;ローカルパス&gt;</code> によりそのディレクトリを指定します。',

    insSetupH: 'セットアップウィザード',
    insSetupP: 'ウィザードは 1 問ずつ尋ねます。既存の値があれば表示され、Enter でそのまま維持できます。',
    insW1H: 'システムと業種',
    insW1P: 'S4 または ECC を選び、ABAP リリースを入力し、15 業種のメニューから選択します。この値が SPRO テーブル・BAPI・TCode と ABAP 構文ゲーティングを決めます。',
    insW2H: 'MCP サーバーのインストール',
    insW2P: '<code>abap-mcp-adt-powerup</code> を <code>&lt;PLUGIN_ROOT&gt;/vendor/abap-mcp-adt/</code> にクローン・ビルドします。既にあればスキップします。',
    insW3H: 'プロファイル作成と接続',
    insW3P: 'alias (<code>KR-DEV</code> 形式を推奨) と tier (<code>DEV</code>・<code>QA</code>・<code>PRD</code>) を決めたうえで、URL・クライアント・認証方式・アカウント・言語を 1 つずつ入力します。RFC バックエンドは soap · native · gateway · odata · zrfc から選択します。',
    insW4H: '接続の検証',
    insW4P: '<code>/mcp</code> で再接続し、<code>GetSession</code> の往復、システム情報の確認、<code>GetInactiveObjects</code> による ADT 権限チェックまで行います。Claude Code の再起動は不要です。',
    insW5H: 'ABAP ユーティリティオブジェクトの作成',
    insW5P: 'DEV プロファイルのみ。<code>ZMCP_ADT_UTILS</code> 関数グループと <code>ZIF_S4SAP_CM</code>・<code>ZCL_S4SAP_CM_*</code> ALV ハンドラを作成します。QA・PRD では拒否し、CTS 移送のガイドを出力します。',
    insW6H: '権限フックのインストール',
    insW6P: 'この手順なしにセットアップは完了しません。<code>block-forbidden-tables.mjs</code> (行抽出ガード) と <code>tier-readonly-guard.mjs</code> (tier 変更ガード) を <code>.claude/settings.json</code> に登録し、双方のスモークテストを実行します。',
    insOptionalH: '任意の手順',
    insOptional1: 'SPRO 設定の抽出。トークン消費は大きいものの、キャッシュが以降のトークン使用量を大幅に削減します',
    insOptional2: 'カスタマイズインベントリ。<code>Z*</code>・<code>Y*</code> の拡張とアペンド構造をスキャンします',
    insOptional3: 'HUD ステータス行。再起動後にアクティブプロファイルと tier、トークン使用量を表示します',
    insSubH: 'サブコマンド',

    insProfileH: 'マルチプロファイル',
    insProfileP: '1 つの Claude Code セッションで複数の SAP 接続を扱えます。接続 1 つがプロファイル 1 つで、プロジェクト側にはどれがアクティブかだけが記録されます。',
    insTier1: '<b>tier が読み取り専用の強制基準です。</b> QA・PRD プロファイルでは <code>Create*</code>・<code>Update*</code>・<code>Delete*</code> がフックと MCP サーバーの 2 層で遮断されます。',
    insTier2: '<b>tier は変更できません。</b> 変えるにはプロファイルを削除して作り直します。',
    insTier3: '<b>パスワードは OS キーチェーンに保存されます。</b> Windows 資格情報マネージャー・macOS キーチェーン・Linux libsecret。キーチェーンが使えない環境ではプロファイル env への平文にフォールバックし、警告を表示します。',

    insDefenseH: '3 層防御',
    insDefenseP: '本番につなぐ前に最初に確認される部分です。文書ではなくコードで強制されます。',
    insL1aH: '行抽出ガード',
    insL1aP: 'Claude Code の <code>PreToolUse</code> フック。プロファイルの <code>blocklistProfile</code> を基準に、機微テーブルへの <code>GetTableContents</code>・<code>GetSqlQuery</code> を拒否します。',
    insL1bH: 'tier 変更ガード',
    insL1bP: 'Claude Code の <code>PreToolUse</code> フック。呼び出しごとにアクティブプロファイルの <code>SAP_TIER</code> を読み直し、QA・PRD での変更を拒否します。状態を保持しません。',
    insL2H: 'MCP サーバー内蔵ガード',
    insL2P: '迂回できない層です。フックが欠けていても設定が誤っていても、<code>abap-mcp-adt-powerup</code> 内部のガードは常に動作します。',
    insDefenseNote: 'L1 フックは IO・パースエラー時にオープンで通し、L2 ガードは常時有効です。推奨の既定値は L1a が <code>strict</code>、MCP サーバーのブロックリストが <code>standard</code> です。',

    insAfterH: 'セットアップ後',
    insAfter1K: 'アクティブシステムの切替',
    insAfter2K: '会社や tier の追加',
    insAfter3K: 'プロファイル一覧',
    insAfter4K: 'ヘルスチェック',
    insAfter5K: 'SPRO の再抽出',

    insMoreH: '関連ドキュメント',
    insMore1: 'インストール原文',
    insMore2: '機能詳細',
    insMore3: '変更履歴'
  });
})();
